### ISSUE TITLE
MyOpenAiAutoConfiguration上的@Primary注解

### ISSUE THREAD

**Issue by 80927187** [404008945/spring-ai-chatgpt#1]
根据我在网上查到的资料，@Primary注解应该加在configuration类的各个@Bean方法上面，而不是直接在configuration类上

**Comment by 404008945** [comment]
> 根据我在网上查到的资料，@primary注解应该加在configuration类的各个@bean方法上面，而不是直接在configuration类上

没错，这个我后面是排除了官方的配置类，来使我自己的配置类生效的，这个注解是无效的。我来去掉
