### ISSUE TITLE
可否支持自定义api hosts

### ISSUE THREAD

**Issue by jaychoubaby** [404008945/spring-ai-chatgpt#2]
使用代理模式请求限制太多，需要自己部署一套代理服务，有公益或者自建的cf的openai wordks代理域名，这种方式看起来更实用一些。

参考：https://github.com/x-dr/chatgptProxyAPI

**Comment by 404008945** [comment]
> 使用代理模式请求限制太多，需要自己部署一套代理服务，有公益或者自建的cf的openai wordks代理域名，这种方式看起来更实用一些。
> 
> 参考：https://github.com/x-dr/chatgptProxyAPI
是支持的哈，改这个配置就好了，用了这个就可以把代理的配置删掉了
![image](https://github.com/404008945/spring-ai-chatgpt/assets/39762246/7718739e-038b-46cd-9610-9a59175a2252)

**Comment by jaychoubaby** [comment]
> > 使用代理模式请求限制太多，需要自己部署一套代理服务，有公益或者自建的cf的openai wordks代理域名，这种方式看起来更实用一些。
> 
> > 
> 
> > 参考：https://github.com/x-dr/chatgptProxyAPI
> 
> 是支持的哈，改这个配置就好了，用了这个就可以把代理的配置删掉了
> 
> ![image](https://github.com/404008945/spring-ai-chatgpt/assets/39762246/7718739e-038b-46cd-9610-9a59175a2252)
> 
> 
> 
> 

收到 感谢回复
